version: '3.8'

services:
  web:
    container_name: go-be
    build:
      context: .
    image: go_be_plgrnd
    command: /bin/sh -c "go run server.go"
    env_file: .env
    ports:
      - 3002:8080
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    env_file: .env
    ports:
      - 5433:5432
    volumes:
        - data-sql:/var/lib/postgresql
  angular_frontend:
    build: ../sports_hub_angular_skeleton
    depends_on:
      - web
    ports:
      - 3000:3000
    restart: always
    environment:
      REACT_APP_API_URL: "http://localhost:3002"
      NG_APP_API_URL: "http://localhost:3002/"

volumes:
  data-sql:
    driver: local